<a href="https://colab.research.google.com/github/shreya24292/uber-booking-analytics-project/blob/main/Uber.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Uploading dataset

In [1]:
from google.colab import files
uploaded =  files.upload()

Saving ncr_ride_bookings.csv to ncr_ride_bookings.csv

##Importing libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

##Load Dataset

In [3]:
df = pd.read_csv('ncr_ride_bookings.csv')

*Verify the data*

In [4]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [5]:
df.tail()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,NaN,NaN,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,NaN,NaN,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,NaN,NaN,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,NaN,NaN,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,NaN,NaN,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [7]:
df.shape

(150000, 21)

*Check missing values*

In [8]:
df.isna().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

###Data Cleaning

*remove quotes from ID*

In [9]:
df['Booking ID'] = df['Booking ID'].str.replace('"','')
df['Customer ID'] = df['Customer ID'].str.replace('"','')

*convert date*

In [10]:
df['Date'] = pd.to_datetime(df['Date'])

*create Date-Time Column*

In [11]:
df['DateTime'] = pd.to_datetime(
    df['Date'].astype(str) + ' ' + df['Time']
)

###Handle missing values

*ratings*

In [12]:
df['Driver Ratings'] = df['Driver Ratings']
df['Customer Rating'] = df['Customer Rating']

*Booking Value & Distance*

In [13]:
df['Booking Value'] = df['Booking Value'].fillna(0)
df['Ride Distance'] = df['Ride Distance'].fillna(0)

*Check Duplicates*

In [14]:
df.duplicated().sum()

np.int64(0)

###Feature Engineering

*Hour of day*

In [15]:
df['Hour'] = df['DateTime'].dt.hour

*Day name*

In [16]:
df['Day'] = df['DateTime'].dt.day_name()

*Month*

In [17]:
df['Month'] = df['DateTime'].dt.month_name()

*Weekend Flag*

In [18]:
df['Weekend'] = df['Day'].isin(
    ['Saturday','Sunday']
)

###Exploratory Data Analysis (EDA)

*Total booking*

In [19]:
df.shape[0]

150000

*Booking Status Distribution*

In [20]:
df['Booking Status'].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

*Vehicle Type Analysis*

In [21]:
df['Vehicle Type'].value_counts()

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

*Revenue Analysis*

In [22]:
df['Booking Value'].sum()

np.float64(51846183.0)

*Distance Analysis*

In [23]:
df['Ride Distance'].describe()

count    150000.000000
mean         16.753168
std          16.291118
min           0.000000
25%           0.000000
50%          13.060000
75%          30.650000
max          50.000000
Name: Ride Distance, dtype: float64

###Cancellation Analysis

*Customer Cancellation Rate*

In [24]:
customer_cancel = (
    df['Cancelled Rides by Customer']
    .notnull()
    .sum()
)

*Driver Cancellation Rate*

In [25]:
driver_cancel = (
    df['Cancelled Rides by Driver']
    .notnull()
    .sum()
)

*Top Customer Cancellation Reasons*

In [26]:
df['Reason for cancelling by Customer'].value_counts()

Reason for cancelling by Customer
Wrong Address                                   2362
Change of plans                                 2353
Driver is not moving towards pickup location    2335
Driver asked to cancel                          2295
AC is not working                               1155
Name: count, dtype: int64

*Top Driver Cancellation Reasons*

In [27]:
df['Driver Cancellation Reason'].value_counts()

Driver Cancellation Reason
Customer related issue                 6837
The customer was coughing/sick         6751
Personal & Car related issues          6726
More than permitted people in there    6686
Name: count, dtype: int64

###Customer Experience Analysis

*Average Customer Rating*

In [28]:
df['Customer Rating'].mean()

np.float64(4.404583870967742)

*Average Driver Rating*

In [29]:
df['Driver Ratings'].mean()

np.float64(4.230992473118278)

*Rating by Vehicle Type*

In [30]:
df.groupby('Vehicle Type')[
    ['Driver Ratings','Customer Rating']
].mean()

               Driver Ratings  Customer Rating
Vehicle Type
Auto                 4.232369         4.402000
Bike                 4.230056         4.403940
Go Mini              4.227694         4.404297
Go Sedan             4.231812         4.409996
Premier Sedan        4.234865         4.403457
Uber XL              4.238340         4.404851
eBike                4.225614         4.403954

###Payment Analysis

In [31]:
df['Payment Method'].value_counts()

Payment Method
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64